version: "2.2"

services:
  link-url-shortener-mongo:
    image: mongo:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - link_url_shortener_db_store:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: AzureDiamond
      MONGO_INITDB_ROOT_PASSWORD: hunter2
    # no --auth is needed here as the presence of username and password add this option automatically
    command: mongod

  link-url-shortener-redis:
    build:
      context: link-url-shortener-redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master

  link-url-shortener-mongo-express:
    image: mongo-express:latest
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: AzureDiamond
      ME_CONFIG_MONGODB_ADMINPASSWORD: hunter2
      ME_CONFIG_MONGODB_SERVER: link-url-shortener-link-url-shortener-mongo-1
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    depends_on:
      - link-url-shortener-mongo

  link-url-shortener-api:
    build:
      context: link-url-shortener-api
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime
      - ./link-url-shortener-api:/app
    ports:
      - 8000:8000
    environment:
      API_PORT: 8000
      UI_PORT: 3000
      API_HOSTNAME: localhost
      UI_HOSTNAME: localhost
      MONGO_PORT: 27017
      MONGO_HOSTNAME: link-url-shortener-link-url-shortener-mongo-1
      MONGO_USERNAME: AzureDiamond
      MONGO_PASSWORD: hunter2
      MONGO_DB_NAME: link-url-shortener-link-url-shortener-mongo-1
      REDIS_PORT: 6379
      REDIS_HOSTNAME: link-url-shortener-link-url-shortener-redis-1
    depends_on:
      - link-url-shortener-mongo
      - link-url-shortener-redis

  link-url-shortener-ui:
    build:
      context: link-url-shortener-ui
      dockerfile: Dockerfile
    volumes:
      - ./link-url-shortener-ui:/app
    ports:
      - 3000:3000

volumes:
  link_url_shortener_db_store: {}
  redis_store: {}
